name: Cypress E2E Coverage

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node14.17.0-chrome88-ff89
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: make install

      - name: Cypress run Chrome
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          browser: chrome
          start: make
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120

      - name: Cypress run Firefox
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
          build: npm run build
          browser: firefox
          start: make
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
